#!/usr/bin/env python3
"""Generate article recency from each tutorial file's latest git commit."""

from __future__ import annotations

import datetime as dt
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
TUTORIALS = ROOT / "_tutorials"
OUTPUT = ROOT / "_data" / "git_order.yml"


def commit_timestamp(path: pathlib.Path) -> int:
    result = subprocess.run(
        ["git", "log", "-1", "--format=%ct", "--", str(path.relative_to(ROOT))],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    value = result.stdout.strip()
    if value.isdigit():
        return int(value)

    # New local files have no commit yet. Keep them visible as latest until
    # their first commit gives them a stable timestamp.
    text = path.read_text(encoding="utf-8")
    front = text.split("---", 2)[1] if text.startswith("---") else ""
    match = re.search(r"^date:\s*[\"']?(\d{4}-\d{2}-\d{2})", front, re.MULTILINE)
    if match:
        return int(dt.datetime.fromisoformat(match.group(1)).replace(tzinfo=dt.timezone.utc).timestamp())
    return int(path.stat().st_mtime)


def main() -> int:
    timestamps = {path.stem: commit_timestamp(path) for path in sorted(TUTORIALS.glob("*.md"))}
    ordered = sorted(timestamps, key=lambda slug: (-timestamps[slug], slug))
    lines = [
        "# Generated by scripts/build_git_order.py.\n",
        "ordered_slugs:\n",
        *[f'  - "{slug}"\n' for slug in ordered],
        "pages:\n",
    ]
    for slug in sorted(timestamps):
        lines.extend([f'  "{slug}":\n', f"    committed_at: {timestamps[slug]}\n"])
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(ordered)} tutorials)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
