#!/usr/bin/env python3
"""Fetch per-article GA4 views for the homepage Popular sort.

Required environment variables:
  GA4_PROPERTY_ID           Numeric GA4 property ID (not the G- measurement ID)
  GA4_SERVICE_ACCOUNT_JSON  Service-account key JSON with Viewer access in GA4

When credentials are absent, the existing data file is left untouched so local
builds and forks remain usable. In CI, the report is refreshed before Jekyll
builds the site.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import pathlib
import re
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parent.parent
TUTORIALS = ROOT / "_tutorials"
DEFAULT_OUTPUT = ROOT / "_data" / "popular.yml"


def article_index() -> dict[str, dict[str, str]]:
    articles: dict[str, dict[str, str]] = {}
    for source in sorted(TUTORIALS.glob("*.md")):
        text = source.read_text(encoding="utf-8")
        front = text.split("---", 2)[1] if text.startswith("---") else ""
        permalink_match = re.search(r"^permalink:\s*[\"']?([^\s\"']+)", front, re.MULTILINE)
        date_match = re.search(r"^date:\s*[\"']?([^\s\"']+)", front, re.MULTILINE)
        permalink = permalink_match.group(1) if permalink_match else f"/tutorials/{source.stem}/"
        if not permalink.endswith("/"):
            permalink += "/"
        articles[source.stem] = {
            "path": permalink,
            "date": date_match.group(1) if date_match else "1970-01-01",
        }
    return articles


def normalize_path(path: str) -> str:
    path = path.split("?", 1)[0].split("#", 1)[0]
    if not path.startswith("/"):
        path = "/" + path
    return path if path.endswith("/") else path + "/"


def fetch_report(property_id: str, service_account_json: str, days: int) -> list[dict[str, Any]]:
    try:
        from google.oauth2 import service_account
        from google.auth.transport.requests import AuthorizedSession
    except ImportError as exc:
        raise RuntimeError("google-auth and requests are required to fetch GA4 data") from exc

    try:
        info = json.loads(service_account_json)
    except json.JSONDecodeError as exc:
        raise RuntimeError("GA4_SERVICE_ACCOUNT_JSON is not valid JSON") from exc

    credentials = service_account.Credentials.from_service_account_info(
        info,
        scopes=["https://www.googleapis.com/auth/analytics.readonly"],
    )
    session = AuthorizedSession(credentials)
    url = f"https://analyticsdata.googleapis.com/v1beta/properties/{property_id}:runReport"
    response = session.post(
        url,
        json={
            "dateRanges": [{"startDate": f"{days}daysAgo", "endDate": "yesterday"}],
            "dimensions": [{"name": "pagePath"}],
            "metrics": [{"name": "screenPageViews"}],
            "limit": 10000,
        },
        timeout=30,
    )
    if not response.ok:
        raise RuntimeError(f"GA4 Data API returned HTTP {response.status_code}: {response.text[:300]}")
    return response.json().get("rows", [])


def yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def display_path(path: pathlib.Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def write_data(output: pathlib.Path, articles: dict[str, dict[str, str]], views: dict[str, int], days: int) -> None:
    ordered = sorted(
        articles,
        key=lambda slug: (-views.get(slug, 0), articles[slug]["date"], slug),
        reverse=False,
    )
    # The key above reverses views only. Resolve equal-view articles by newest date.
    ordered = sorted(ordered, key=lambda slug: articles[slug]["date"], reverse=True)
    ordered = sorted(ordered, key=lambda slug: views.get(slug, 0), reverse=True)

    lines = [
        "# Generated by scripts/fetch_ga4_popularity.py.\n",
        f"generated_at: {yaml_quote(dt.datetime.now(dt.timezone.utc).isoformat(timespec='seconds'))}\n",
        f"window_days: {days}\n",
        "metric: screenPageViews\n",
        "ordered_slugs:\n",
    ]
    lines.extend(f"  - {yaml_quote(slug)}\n" for slug in ordered)
    lines.append("pages:\n")
    for slug in sorted(articles):
        lines.extend(
            [
                f"  {yaml_quote(slug)}:\n",
                f"    path: {yaml_quote(articles[slug]['path'])}\n",
                f"    views: {views.get(slug, 0)}\n",
            ]
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--days", type=int, default=30)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--strict", action="store_true", help="fail instead of retaining fallback data")
    args = parser.parse_args()

    articles = article_index()
    property_id = os.environ.get("GA4_PROPERTY_ID", "").strip()
    service_json = os.environ.get("GA4_SERVICE_ACCOUNT_JSON", "").strip()

    if not property_id or not service_json:
        if args.output.exists():
            print(f"GA4 credentials not configured; keeping {display_path(args.output)}")
            return 0
        if args.strict:
            print("GA4_PROPERTY_ID and GA4_SERVICE_ACCOUNT_JSON are required", file=sys.stderr)
            return 1
        write_data(args.output, articles, {}, args.days)
        print(f"GA4 credentials not configured; wrote zero-view fallback to {display_path(args.output)}")
        return 0

    try:
        rows = fetch_report(property_id, service_json, args.days)
        path_to_slug = {normalize_path(meta["path"]): slug for slug, meta in articles.items()}
        views = {slug: 0 for slug in articles}
        for row in rows:
            path = normalize_path(row["dimensionValues"][0]["value"])
            slug = path_to_slug.get(path)
            if slug:
                views[slug] += int(row["metricValues"][0]["value"])
        write_data(args.output, articles, views, args.days)
        print(f"wrote {display_path(args.output)} with {sum(views.values())} article views")
        return 0
    except Exception as exc:  # Keep deploys working if Analytics is temporarily unavailable.
        print(f"WARNING: could not refresh GA4 popularity: {exc}", file=sys.stderr)
        if args.strict or not args.output.exists():
            return 1
        print(f"keeping existing {display_path(args.output)}", file=sys.stderr)
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
